name: dm4bem-env

channels:
  - conda-forge

dependencies:
  - python=3.13.7
  - jupyter=1.0.0
  - jupyterlab=4.0.11
  - matplotlib=3.10.7
  - numpy=2.3.4
  - scipy=1.16.2
  - pandas=2.3.3
  - control=0.10.0
